version: "3.3"

networks:
  nginx:
    external:
      name: nginx

services:

  tileserver-gl:
    image: "maptiler/tileserver-gl"
    container_name: tileserver-gl
    restart: always
    command:
      - --port
      - "80"
      - --mbtiles
      - "${MBTILES_FILE}"
      - --verbose
      - -c
      - /data/tileserver-gl.json
      - --public_url=https://tileserver.cyclemap.us/
      - --log_file=/var/log/access.log
      - --log_format=combined
    environment:
      VIRTUAL_HOST: tileserver.cyclemap.us
      LETSENCRYPT_HOST: tileserver.cyclemap.us
      HTTPS_METHOD: redirect
      ENABLE_IPV6: "false"
    networks:
      - nginx
    volumes:
      - ./data-tileserver:/data
      - ./data-tileserver/viewer:/app/public/resources/viewer
      - ./logs:/var/log

